language: generic 
sudo: required
services:
  -docker

before_install:
  - docker build -t messbah/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true messbah/docker-react npm run test